name: Update Excel and Publish Pending Count (Java)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  process_excel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install gdown for downloading Excel file
      run: pip install gdown

    - name: Download Excel file from Google Drive
      run: |
        gdown "${{ secrets.EXCEL_URL_LINK }}" -O timetable.xlsm
        
    - name: Move Excel file into java_services directory
      run: |
        mv timetable.xlsm ./java_services/timetable.xlsm

    - name: Run Java Maven project to update Excel
      working-directory: ./java_services
      run: |
        mvn clean package
        mvn exec:java

    - name: Upload pending count
      uses: actions/upload-artifact@v4
      with:
        name: pending-count
        path: pending_output.txt
